version: '3.4'
services:
        nginx:
                build: ./requirements/nginx
                container_name: nginx
                depends_on:
                        - wordpress
                ports: 
                        - "443:443"
                restart: always
                networks:
                        - frontend
                volumes: 
                   - type: volume
                     source: website
                     target: /var/www
        wordpress:
                build: ./requirements/wordpress
                environment:
                        - WP_ADMIN=${WP_ADMIN}
                        - WP_ADPASS=${WP_ADPASS}
                        - WP_USER=${WP_USER}
                        - WP_USPASS=${WP_USPASS}
                        - DB_NAME=${DB_NAME}
                        - DB_USER=${DB_USER}
                        - DB_PASS=${DB_PASS}
                        - ROOT_PASS=${ROOT_PASS}
                container_name: wordpress
                depends_on:
                        - mariadb
                restart: always
                networks:
                        - frontend
                        - backend
                volumes:
                        - type: volume
                          source: website
                          target: /var/www

        mariadb:
                build: 
                        context: ./requirements/mariadb
                        args:
                                - DB_NAME=${DB_NAME}
                                - DB_USER=${DB_USER}
                                - DB_PASS=${DB_PASS}
                                - ROOT_PASS=${ROOT_PASS}

                container_name: mariadb
                restart: always
                networks:
                        - backend
                volumes:
                        - type: volume
                          source: database
                          target: /var/lib/mysql

networks:
        frontend:
        backend:
volumes:
        website:
                driver_opts:
                      type: "none"
                      o: "bind"
                      device: "/home/aleconte/data/code"
        database:
                driver_opts:
                      type: "none"
                      o: "bind"
                      device: "/home/aleconte/data/data"
