version: '3.4'
services:
        nginx:
                build: ./requirements/nginx
                container_name: nginx
                ports: 
                        - "80:80"
                networks:
                        - frontend
                volumes: 
                   - type: volume
                     source: website
                     target: /var/www
        wordpress:
                build: ./requirements/wordpress
                container_name: wordpress
                networks:
                        - frontend
                        - backend
                volumes:
                        - type: volume
                          source: website
                          target: /var/www

        mariadb:
                build: ./requirements/mariadb
                container_name: mariadb
                networks:
                        - backend
                volumes:
                        - type: volume
                          source: database
                          target: /var/lib/mysql

networks:
        frontend:
        backend:
volumes:
        website:
                driver_opts:
                      type: "none"
                      o: "bind"
                      device: "/home/user42/Documents/inception2/srcs/requirements/code"
        database:
                driver_opts:
                      type: "none"
                      o: "bind"
                      device: "/home/user42/Documents/inception2/srcs/requirements/data"
