version: '3'
services:
        nginx:
                build: ./requirements/nginx
                container_name: nginx
                ports: 
                        - "80:80"
                networks:
                        - frontend
                volumes: 
                        - ./requirements/code:/var/www
        wordpress:
                build: ./requirements/wordpress
                container_name: wordpress
                networks:
                        - frontend
                        - backend
                volumes:
                        - ./requirements/code:/var/www
        mariadb:
                build: ./requirements/mariadb
                container_name: mariadb
                networks:
                        - backend
                          #volumes:
                          # - ./requirements/data:/var/lib/mysql
networks:
        frontend:
        backend:
