version: '3'
services:
        nginx:
                build: ./requirements/nginx
                container_name: nginx
                ports: 
                        - "80:80"
                networks:
                        - frontend
                volumes: 
                        - ./requirements/code:/var/www
        wordpress:
                build: ./requirements/wordpress
                container_name: wordpress
                ports:
                        - "9000"
                networks:
                        - frontend
                volumes:
                        - ./requirements/code:/var/www
networks:
        frontend:
        backend:
